--- # Debug example
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  connection: ssh
  tasks:
    - name: install web server
      yum: name=httpd state=installed
    - debug: msg="Equivilant of sudo yum install httpd"
    - name: how long has the system been up
      shell: /usr/bin/uptime
      register: result
    - debug: var=result
