--- # DNF example
- hosts: apacheb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install apache web server with DNF
      dnf: name=httpd state=latest
      //// abscent to remove it
      - name: dnf update
        dnf: name=* state=latest
        
