--- # htpasswd exampel
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: install the python dependencies
      apt: pkg=python-passlib state=latest
    - name: adding a user to web site authentication
      htpasswd: path=/etc/apache2/.htpasswd name=test2 password=password owner=test2 group=test2 mode=064
    - name: remove a user from  web site authentication
      htpasswd: path=/etc/apache2/.htpasswd name=test2 state=abscent
      
