--- # jinja2 module example ( extention of python that allows to templatize our configuration)
- host: apapcheweb:debian
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    userName: test
    userPassword: password1
    connectionType: SFTP
  tasks:
    - name: Install the configuration file customized for the system
      template: src=jinja2_configuration_file.conf.j2 dest=/home/test/jinja2_configuration_file.conf owner=test group=test mode=750
